#!/usr/bin/env node
// Reads every src/db/migrations/*.sql file and emits a sibling
// src/db/migrations/sql-strings.ts module that re-exports each SQL
// payload as a string literal. The runtime migrations.js loads from
// the generated module instead of importing .sql directly — Metro
// can bundle JS strings, but doesn't have a transformer for .sql.
//
// Run via `npm run build:migrations`. The output is committed so that
// EAS builds don't need a Node toolchain in the bundling step.
//
// Test setups that use drizzle-orm/better-sqlite3 keep reading the
// raw .sql files via `migrate(db, { migrationsFolder })` and stay
// untouched.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const MIGRATIONS_DIR = path.resolve(ROOT, 'src', 'db', 'migrations');
const OUTPUT = path.resolve(MIGRATIONS_DIR, 'sql-strings.ts');

const files = fs
  .readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith('.sql'))
  .sort();

if (files.length === 0) {
  console.error('no .sql files found in', MIGRATIONS_DIR);
  process.exit(1);
}

const exports: string[] = [];
for (const file of files) {
  const constName = `M_${file
    .replace(/\.sql$/, '')
    .replace(/[^A-Za-z0-9_]/g, '_')
    .toUpperCase()}`;
  const sqlText = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');
  exports.push(`export const ${constName} = ${JSON.stringify(sqlText)};`);
}

const banner = `// AUTO-GENERATED by scripts/generate-migration-strings.ts.\n// Do NOT edit by hand — run \`npm run build:migrations\` to regenerate.\n\n`;
fs.writeFileSync(OUTPUT, banner + exports.join('\n') + '\n', 'utf-8');
console.log('wrote', path.relative(ROOT, OUTPUT), 'with', files.length, 'migration(s)');
